schema_version = 1.1

[mods.modId]
name = "unknown" # Name of the mod
notes = [""] # Note/description for the mod, put whatever you want here or leave empty. Can have more than one note
priority = 0 # Priority of the mod. 0 is unknown, lower values more important

file = "aether-1.20.1-1.5.2-neoforge.jar" # Exact name of .jar file
version = "unknown" # Mod version
loader = "neoforge" # Options: neoforge, fabric, unknown
side = "both" # Options: client, server, both, unknown

importance = "required" # How required the mod is. Options: required, reccomended, optional, unknown
impact = "heavy" # Performance impact of the mod. Options: heavy, light, performance, unknown

requirements = ["unknown"] # Requirements for the mod to run
recommends = ["unknown"] # Recommended mods