[header]
schema_version = "2.1.0"
pack_version = "1.0.0"

[customization]
tag_categories = []

[customization.standard_tags.simple]
favorite = { description = "Marks mod as favorite"}

[customization.standard_tags.value]
importance = ["required", "recommended", "optional"]
impact = ["light", "heavy", "performance"]

[customization.default_tags.simple]

[customization.default_tags.value]
